# Server Port Configuration
server:
  port: 8080

#Application Name
spring:
  application:
    name: prod

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/crud_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
