name: Test [Test]

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests -P test

  package:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: packing application
        run: mvn -B package --file pom.xml -DskipTests -P test

  test:
    needs: [ package ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Application Clean Install
        run: mvn clean install -DskipTests -P test

      - name: Application Test
        run: mvn -B package --file pom.xml -P test

      - name: Docker Registry Application files
        run: ls -lha

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/crud .

      - name: Publish Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/crud

      - name: Create Pull Request
        run: gh pr create -B master -H test --title 'Pull Request test into master' --body '[Pull Request Realizado] Para Merge com a Branch Principal [master]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET_KEY }}